/*
 * generated by Xtext
 */
package org.ats_lang.ui;

import org.ats_lang.ui.editor.syntaxcoloring.AtsAntlrTokenToAttributeIdMapper;
import org.ats_lang.ui.editor.syntaxcoloring.AtsIHighlightingConfiguration;
import org.ats_lang.ui.editor.syntaxcoloring.AtsISemanticHighlightingCalculator;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;



/**
 * Use this class to register components to be used within the IDE.
 */
public class AnairiatsDatsUiModule extends org.ats_lang.ui.AbstractAnairiatsDatsUiModule {
	public AnairiatsDatsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return AtsIHighlightingConfiguration.class;
	}

	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
		return AtsAntlrTokenToAttributeIdMapper.class;
	}
	
	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
		return AtsISemanticHighlightingCalculator.class;
	}
	
	
//	public Provider<IAllContainersState> provideIAllContainerState() {
//		return org.eclipse.xtext.ui.shared.Access.getWorkspaceProjectsState();
//	}
	
//	  @Override
//	  public Class<? extends ILocationInFileProvider> 
//	          bindILocationInFileProvider() {
//	    return MyDslLocationInFileProvider.class;
//	  }
}
