/*
* generated by Xtext
*/
package org.ats_lang.ui.contentassist;

import org.ats_lang.ui.contentassist.AbstractAnairiatsDatsProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class AnairiatsDatsProposalProvider extends AbstractAnairiatsDatsProposalProvider {

}
