/*
 * generated by Xtext
 */
package org.ats_lang.scoping;


/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping on
 * how and when to use it
 * 
 */
public class AnairiatsDatsScopeProvider extends AnairiatsSatsScopeProvider {
	
	
}
