/*
 * generated by Xtext
 */
package org.ats_lang.ui.outline;

import org.ats_lang.anairiatsDats.*;
import org.ats_lang.anairiatsSats.*;
import org.eclipse.emf.common.util.EList;
import org.eclipse.xtext.ui.editor.outline.IOutlineNode;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.outline.impl.DocumentRootNode;

/**
 * customization of the default outline structure
 * 
 */
public class AnairiatsDatsOutlineTreeProvider extends
		DefaultOutlineTreeProvider {
	protected void _createChildren(DocumentRootNode parentNode,
			dynprogram dynprog) {
		d0ecseq_dyn_rec elements = dynprog.getM_dyn();
		if (elements == null) {
			System.out.println("elements == null");
			return;
		}
		createNode(parentNode, elements);

	}

	protected void _createChildren(IOutlineNode parentNode,
			d0ecseq_dyn_rec ele) {
		EList<d0ecseq_dyn> dynlst = ele.getM_d0ec_dyn();
		for (d0ecseq_dyn node : dynlst) {
			// System.out.println("========= " + node.getClass().getName());
			if (node instanceof d0ecseq_dyn_d0ec) {
				createNode(parentNode, ((d0ecseq_dyn_d0ec) node).getM_d0ec());
				continue;
			} else {
				createNode(parentNode, node);
			}
			if (node instanceof d0ecseq_dyn_ext) {
				andd0cstdecseq m_rec_d0cstdec = ((d0ecseq_dyn_ext) node)
						.getM_rec_d0cstdec();
				EList<d0cstdec> m_andd0cstdecseq = m_rec_d0cstdec
						.getM_andd0cstdecseq();
				for (d0cstdec dec : m_andd0cstdecseq) {
					createNode(parentNode, dec);
				}
				continue;
			}

			if (node instanceof d0ecseq_dyn_val) {
				andv0aldecseq m_rec_v0aldec = ((d0ecseq_dyn_val) node)
						.getM_rec_v0aldec();
				EList<v0aldec> m_andv0aldecseq = m_rec_v0aldec.getM_andv0aldecseq();
				for (v0aldec vdec : m_andv0aldecseq) {
					createNode(parentNode, vdec);
				}
				continue;
			}

			if (node instanceof d0ecseq_dyn_val_par) {
				andv0aldecseq m_rec_v0aldec = ((d0ecseq_dyn_val_par) node)
						.getM_rec_v0aldec();
				EList<v0aldec> m_andv0aldecseq = m_rec_v0aldec.getM_andv0aldecseq();
				for (v0aldec vdec : m_andv0aldecseq) {
					createNode(parentNode, vdec);
				}
				continue;
			}
			if (node instanceof d0ecseq_dyn_val_rec) {
				andv0aldecseq m_rec_v0aldec = ((d0ecseq_dyn_val_rec) node)
						.getM_rec_v0aldec();
				EList<v0aldec> m_andv0aldecseq = m_rec_v0aldec.getM_andv0aldecseq();
				for (v0aldec vdec : m_andv0aldecseq) {
					createNode(parentNode, vdec);
				}
				continue;
			}

			if (node instanceof d0ecseq_dyn_fun) {
				andf0undecseq m_rec_fundec = ((d0ecseq_dyn_fun) node)
						.getM_rec_fundec();
				EList<f0undec> m_f0undec = m_rec_fundec.getM_f0undec();
				for (f0undec fdec : m_f0undec) {
					createNode(parentNode, fdec);
				}
				continue;
			}

			if (node instanceof d0ecseq_dyn_var) {
				andv0ardecseq m_rec_v0ardec = ((d0ecseq_dyn_var) node)
						.getM_rec_v0ardec();
				EList<v0ardec> m_f0undec = m_rec_v0ardec.getM_v0ardec();
				for (v0ardec vdec : m_f0undec) {
					createNode(parentNode, vdec);
				}
				continue;
			}
		}

	}

	protected void _createChildren(IOutlineNode parentNode, d0ecseq_dyn_ext ele) {
		d0ecargseq m_d0ecargseq = ele.getM_d0ecargseq();
		// tempalte args
		createNode(parentNode, m_d0ecargseq);
	}
}
