/*
 * generated by Xtext
 */
package org.ats_lang.ui.labeling;

import org.ats_lang.anairiatsSats.andd0cstdecseq;
import org.ats_lang.anairiatsSats.d0cstdec;
import org.ats_lang.anairiatsSats.d0ec_sta;
import org.ats_lang.anairiatsSats.d0ecargseq;
import org.ats_lang.anairiatsSats.d0ecseq_sta;
import org.ats_lang.anairiatsSats.d0ecseq_sta_rev;
import org.ats_lang.anairiatsSats.dcstkind;
import org.ats_lang.anairiatsSats.satprogram;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class AnairiatsSatsLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public AnairiatsSatsLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	String text(satprogram ele) {
		return "satprogram";
	}

	String text(d0ecseq_sta ele) {
		return "Program";
	}

	String text(d0ec_sta ele) {
		if (ele.getM_d0ec() != null) {
			return "d0ec_sta, d0ec";
		}
		
		dcstkind m_kind = ele.getM_kind();
		if (m_kind != null) {
			return m_kind.getM_kind();
		}
		
		return "d0ec_sta";
		
//	    m_d0ec=d0ec
//	    | m_kind=dcstkind// fun
//	      m_tmparg=d0ecargseq  // {n: type}
//	      m_d0cstdec=d0cstdec   // foo {k: int} (x: int k):<fun> int = "xxx"
//	      m_seq=andd0cstdecseq  // 
//	    | m_extcode=LITERAL_extcode
//	    | srpifkind guad0ec_sta  // #ifdef X #then ... #elif ... #else ... #endif
//	    | SRPINCLUDE m_include=LITERAL_string
//	    | LOCAL m_local=d0ecseq_sta IN m_body=d0ecseq_sta END
	}

	String text(d0ecseq_sta_rev ele) {
		return "d0ecseq_sta_rev";
	}

	String text(dcstkind ele) {
		return ele.getM_kind();
	}

	String text(d0ecargseq ele) {
		return "d0ecargseq";
	}

	String text(d0cstdec ele) {
		return "d0cstdec";
	}

	String text(andd0cstdecseq ele) {
		return "andd0cstdecseq";
	}

	/*
	 * //Labels and icons can be computed like this:
	 * 
	 * String image(MyModel ele) { return "MyModel.gif"; }
	 */
}
