/*
 * generated by Xtext
 */
package org.ats_lang;

import org.ats_lang.naming.AnairiatsDatsQualifiedNameProvider;
import org.eclipse.xtext.resource.IContainer;
import org.eclipse.xtext.resource.containers.StateBasedContainerManager;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AnairiatsDatsRuntimeModule extends org.ats_lang.AbstractAnairiatsDatsRuntimeModule {
	@Override
	public Class<? extends org.eclipse.xtext.naming.IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return AnairiatsDatsQualifiedNameProvider.class;
	}
	
//	public Class<? extends IContainer.Manager>bindIContainer$Manager() {
//		return StateBasedContainerManager.class;
//	}
}
